
from Public.Base import web二次封装
import  time,random

浏览器=web二次封装('Edge') #实例化 创建对象      就好像盖房子要根据之前设计的图纸来
浏览器.打开地址('http://39.102.208.214/haidao') # 调用方法
浏览器.点击元素('text','注册')
浏览器.输入内容('name','username','lisi'+str(random.randint(1000,9999)))
浏览器.输入内容('name','password','123456')
浏览器.输入内容('name','pwdconfirm','123456')
浏览器.输入内容('name','email','123'+str(random.randint(1000,9999))+'@qq.com')
浏览器.输入内容('name','mobile','178'+str(random.randint(10000000,99999999)))
浏览器.点击元素('id','popup-submit')
# 浏览器.点击元素('text','登录')
# 浏览器.输入内容('name','username','lisi')
# 浏览器.输入内容('name','password','123456')
浏览器.点击元素('id','popup-submit')
浏览器.点击元素('text','返回商城首页')
浏览器.点击元素('xpath','/html/body/div[5]/div[1]/div/ul/li/div[1]/a/img')
浏览器.点击元素('text','立即购买')
浏览器.点击元素('xpath','/html/body/div[3]/div[2]/dl[1]/dd/div/a')
浏览器.切换框架('xpath','/html/body/div[7]/div/table/tbody/tr[2]/td/div/iframe')
浏览器.点击元素('xpath','/html/body/form/div[1]/ul/li[1]/div/div/div[2]/div[2]')
浏览器.点击元素('text','广西')
浏览器.点击元素('text','南宁')
浏览器.点击元素('text','西乡塘')
浏览器.点击元素('text','西乡塘街道')
浏览器.输入内容('xpath','/html/body/form/div[1]/ul/li[2]/div/textarea','荣华大厦313')
浏览器.输入内容('xpath','/html/body/form/div[1]/ul/li[3]/div/input','李四')
浏览器.输入内容('xpath','/html/body/form/div[1]/ul/li[4]/div/input','13800000000')
浏览器.输入内容('xpath','/html/body/form/div[1]/ul/li[5]/div/input','533800')
浏览器.点击元素('name','default')
浏览器.点击元素('id','hold')
浏览器.driver.switch_to.default_content()
time.sleep(3)
浏览器.点击元素('text','货到付款')
浏览器.点击元素('id','submit')
浏览器.点击元素('text','查看订单')

浏览器.打开地址('http://39.102.208.214/haidao/index.php?m=admin&c=index&a=index')
浏览器.输入内容('name','username','admin')
浏览器.输入内容('name','password','111111')
浏览器.点击元素('name','dosubmit')
浏览器.点击元素('text','订单')
浏览器.切换框架('xpath','/html/body/div[4]/iframe')
浏览器.点击元素('text','待确认')
浏览器.点击元素('text','查看')
浏览器.点击元素('xpath','/html/body/div[2]/table[1]/tbody/tr[1]/th/div/button[1]')
浏览器.切换默认框架()
浏览器.切换框架('xpath','/html/body/div[6]/div/table/tbody/tr[2]/td/div/iframe')
浏览器.点击元素('id','okbtn')
time.sleep(3)
浏览器.切换默认框架()
浏览器.切换框架('xpath','/html/body/div[4]/iframe')
浏览器.点击元素('xpath','/html/body/div[2]/table[1]/tbody/tr[1]/th/div/button[2]')

浏览器.切换默认框架()
浏览器.切换框架('xpath','/html/body/div[6]/div/table/tbody/tr[2]/td/div/iframe')
浏览器.点击元素('name','o_sku_id[]')
浏览器.输入内容('name','delivery_sn','1234567890')
浏览器.点击元素('id','okbtn')

浏览器.切换默认框架()
time.sleep(3)
浏览器.关闭浏览器()